/*
 * Generates tests/vectors/ntt_pqclean_kat.h from PQClean's ml-kem-512
 * reference implementation (the standardized FIPS 203 successor to
 * CRYSTALS-Kyber, formerly crypto_kem/kyber512).
 *
 * This file is NOT part of the numx library. It links against PQClean's
 * ntt.c and reduce.c to produce fixture vectors that numx's own tests
 * check against, closing the external-reference-validation gap described
 * in validation/reference/ntt/README.md. It is never built as part of
 * the numx library or its CI, so it does not affect numx's zero
 * external-dependency guarantee.
 *
 * Usage: see README.md in this directory for the exact clone/build/run
 * steps and the pinned PQClean commit.
 *
 * The chain below (ntt -> poly_reduce -> basemul_montgomery ->
 * invntt_tomont -> poly_reduce) mirrors PQClean's own indcpa.c usage
 * (see indcpa.c: polyvec_basemul_acc_montgomery + poly_invntt_tomont +
 * poly_reduce), which is the reference implementation's real polynomial-
 * multiplication path, not a bespoke construction.
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "ntt.h"
#include "params.h"
#include "reduce.h"

/* Matches numx's tests/test_ntt.c priv_lcg exactly, so the same seeds
 * produce the same input polynomials on both sides. */
static uint32_t priv_lcg(uint32_t *s)
{
    *s = *s * 1664525u + 1013904223u;
    return *s;
}

static void rand_poly(int16_t *f, uint32_t *seed)
{
    int i;
    for (i = 0; i < KYBER_N; i++)
        f[i] = (int16_t)(priv_lcg(seed) % (uint32_t)KYBER_Q);
}

/* Canonicalize a centered-representative coefficient into [0, q). */
static int16_t canon(int16_t v)
{
    v = PQCLEAN_MLKEM512_CLEAN_barrett_reduce(v);
    if (v < 0) v += KYBER_Q;
    return v;
}

static void print_array(const char *name, const int16_t *v)
{
    int i;
    printf("static const numx_q15_t %s[256] = {\n", name);
    for (i = 0; i < 256; i++)
    {
        printf("%d,", v[i]);
        if ((i + 1) % 16 == 0) printf("\n");
    }
    printf("};\n\n");
}

static void gen_vector(uint32_t seed, int idx)
{
    int16_t a[256], b[256];
    int16_t ntt_a[256];
    int16_t prod[256];
    int i;
    char name[64];
    uint32_t working_seed = seed;

    rand_poly(a, &working_seed);
    rand_poly(b, &working_seed);

    /* Forward NTT of a, canonicalized. */
    memcpy(ntt_a, a, sizeof(a));
    PQCLEAN_MLKEM512_CLEAN_ntt(ntt_a);
    for (i = 0; i < 256; i++) ntt_a[i] = canon(ntt_a[i]);

    /* Full negacyclic polynomial multiply a*b, canonicalized. */
    {
        int16_t aa[256], bb[256];
        memcpy(aa, a, sizeof(a));
        memcpy(bb, b, sizeof(b));

        PQCLEAN_MLKEM512_CLEAN_ntt(aa);
        for (i = 0; i < 256; i++) aa[i] = canon(aa[i]);
        PQCLEAN_MLKEM512_CLEAN_ntt(bb);
        for (i = 0; i < 256; i++) bb[i] = canon(bb[i]);

        for (i = 0; i < KYBER_N / 4; i++)
        {
            PQCLEAN_MLKEM512_CLEAN_basemul(&prod[4 * i], &aa[4 * i], &bb[4 * i],
                                            PQCLEAN_MLKEM512_CLEAN_zetas[64 + i]);
            PQCLEAN_MLKEM512_CLEAN_basemul(&prod[4 * i + 2], &aa[4 * i + 2], &bb[4 * i + 2],
                                            (int16_t)(-PQCLEAN_MLKEM512_CLEAN_zetas[64 + i]));
        }
        PQCLEAN_MLKEM512_CLEAN_invntt(prod);
        for (i = 0; i < 256; i++) prod[i] = canon(prod[i]);
    }

    printf("/* seed = %u */\n", seed);
    snprintf(name, sizeof(name), "ntt_pqclean_a_%d", idx);
    print_array(name, a);
    snprintf(name, sizeof(name), "ntt_pqclean_b_%d", idx);
    print_array(name, b);
    snprintf(name, sizeof(name), "ntt_pqclean_ntt_a_%d", idx);
    print_array(name, ntt_a);
    snprintf(name, sizeof(name), "ntt_pqclean_polymul_%d", idx);
    print_array(name, prod);
}

int main(void)
{
    static const uint32_t seeds[] = {1u, 42u, 12345u, 999983u, 2026u};
    int i;

    printf("/**\n");
    printf(" * @file ntt_pqclean_kat.h\n");
    printf(" * @brief External-reference NTT test vectors.\n");
    printf(" *\n");
    printf(" * Generated by validation/reference/ntt/generate_ntt_pqclean_vectors.c\n");
    printf(" * against PQClean's ml-kem-512 \"clean\" reference implementation\n");
    printf(" * (FIPS 203 / formerly CRYSTALS-Kyber-512), NOT against numx's own\n");
    printf(" * code. See validation/reference/ntt/README.md for provenance,\n");
    printf(" * the pinned PQClean commit, and regeneration steps.\n");
    printf(" */\n\n");
    printf("#ifndef NUMX_TEST_VECTORS_NTT_PQCLEAN_KAT_H\n");
    printf("#define NUMX_TEST_VECTORS_NTT_PQCLEAN_KAT_H\n\n");
    printf("#include \"numx/numx_types.h\"\n\n");

    for (i = 0; i < (int)(sizeof(seeds) / sizeof(seeds[0])); i++)
        gen_vector(seeds[i], i);

    printf("#endif /* NUMX_TEST_VECTORS_NTT_PQCLEAN_KAT_H */\n");
    return 0;
}
